In [8]:
import os 
import pandas as pd
import numpy as np

from popy.config import PROJECT_PATH_LOCAL
from popy.io_tools import load_behavior_yuri
from popy.behavior_data_tools import add_stay_value

In [ ]:
'''floc_raw = os.path.join(PROJECT_PATH_LOCAL, 'data', 'processed', 'behavior', 'REALValue_df.csv')

data = pd.read_csv(floc_raw)

# reorder columns to [monkey, injection, session, trial, block, targ_best, targ_action, Rew]
data = data[['monkey', 'injection', 'session', 'trial', 'block', 'targ_best', 'targ_action', 'Rew']]

data['monkey'] = 'yu'
data['monkey'] = [data['monkey'][i] + '_' + data['injection'][i] for i in range(len(data))]
data.sort_values(by=['monkey', 'session', 'trial'], inplace=True)
data.drop(columns=['injection'], inplace=True)
data['session'] = data['session'].astype(str)
data.rename(columns={'trial': 'trial_id'}, inplace=True)  
data.rename(columns={'block': 'block_id'}, inplace=True)
data.rename(columns={'targ_best': 'best_target'}, inplace=True)
data.rename(columns={'targ_action': 'target'}, inplace=True)
data.rename(columns={'Rew': 'feedback'}, inplace=True)
data['block_id'] = data['block_id'] - 1
#data['trial_id'] = data['trial_id'] - 1


# if tarhet is null, set feedback to null as well
data['feedback'] = np.where(data['target'].isnull(), np.nan, data['feedback'])

data = data.sort_values(by=['monkey', 'session', 'trial_id'])

floc_save = os.path.join(PROJECT_PATH_LOCAL, 'data', 'processed', 'behavior', 'behavior_yuri.pkl')
data.to_pickle(floc_save)
print(f"Saved {floc_save}")

data'''

Saved /Users/zsombi/Library/CloudStorage/GoogleDrive-uuungvarszi@gmail.com/Other computers/My Mac/ZSOMBI/SBRI/PoPy/data/processed/behavior/behavior_yuri.pkl

        monkey session  trial_id  block_id  best_target  target  feedback
0       yu_DCZ      10         1         0            1       3       0.0
1       yu_DCZ      10         2         0            1       3       1.0
2       yu_DCZ      10         3         0            1       2       0.0
3       yu_DCZ      10         4         0            1       1       1.0
4       yu_DCZ      10         5         0            1       1       0.0
...        ...     ...       ...       ...          ...     ...       ...
22899  yu_sham      71       535        12            3       3       1.0
22900  yu_sham      71       536        12            3       3       1.0
22901  yu_sham      71       537        12            3       3       1.0
22902  yu_sham      71       538        12            3       3       1.0
22903  yu_sham      71       539        12            3       3       1.0

[23415 rows x 7 columns]

In [12]:
behav_yuri = load_behavior_yuri()
behav_yuri = add_stay_value(behav_yuri)
behav_yuri = behav_yuri.rename(columns={'stay_value': 'value'})
behav_yuri = behav_yuri.drop(columns=['stay_proba'])
# save as behavior_data_to_clemece.csv
behav_yuri

,monkey,session,trial_id,block_id,best_target,target,feedback,value
0,yu_DCZ,10,1,0,1,3,0.0,0.128366
1,yu_DCZ,10,2,0,1,3,1.0,0.064920
2,yu_DCZ,10,3,0,1,2,0.0,0.527095
3,yu_DCZ,10,4,0,1,1,1.0,0.064920
4,yu_DCZ,10,5,0,1,1,0.0,0.559182
...,...,...,...,...,...,...,...,...
23410,yu_sham,71,535,12,3,3,1.0,0.862862
23411,yu_sham,71,536,12,3,3,1.0,0.924762
23412,yu_sham,71,537,12,3,3,1.0,0.958722
23413,yu_sham,71,538,12,3,3,1.0,0.977354
23414,yu_sham,71,539,12,3,3,1.0,0.987576

In [ ]:
'''floc_raw = os.path.join(PROJECT_PATH_LOCAL, 'data', 'processed', 'behavior', 'Yuri_valueRewNEW.csv')

data = pd.read_csv(floc_raw)

# reorder columns to [monkey, injection, session, trial, block, targ_best, targ_action, Rew]
data = data[['monkey', 'injection', 'session', 'trial', 'block', 'targ_best', 'targ_action', 'Rew']]

data['monkey'] = 'yu'
data['monkey'] = [data['monkey'][i] + '_' + data['injection'][i] for i in range(len(data))]
data.sort_values(by=['monkey', 'session', 'trial'], inplace=True)
data.drop(columns=['injection'], inplace=True)
data['session'] = data['session'].astype(str)
data.rename(columns={'trial': 'trial_id'}, inplace=True)  
data.rename(columns={'block': 'block_id'}, inplace=True)
data.rename(columns={'targ_best': 'best_target'}, inplace=True)
data.rename(columns={'targ_action': 'target'}, inplace=True)
data.rename(columns={'Rew': 'feedback'}, inplace=True)
data['block_id'] = data['block_id'] - 1
#data['trial_id'] = data['trial_id'] - 1


# if tarhet is null, set feedback to null as well
data['feedback'] = np.where(data['target'].isnull(), np.nan, data['feedback'])

data = data.sort_values(by=['monkey', 'session', 'trial_id'])

floc_save = os.path.join(PROJECT_PATH_LOCAL, 'data', 'processed', 'behavior', 'behavior_yuri.pkl')
data.to_pickle(floc_save)
print(f"Saved {floc_save}")

data'''

Saved /Users/zsombi/Library/CloudStorage/GoogleDrive-uuungvarszi@gmail.com/Other computers/My Mac/ZSOMBI/SBRI/PoPy/data/processed/behavior/behavior_yuri.pkl

        monkey session  trial_id  block_id  best_target  target  feedback
0       yu_DCZ      10         0         0            1     NaN       NaN
1       yu_DCZ      10         1         0            1     3.0       0.0
2       yu_DCZ      10         2         0            1     3.0       1.0
3       yu_DCZ      10         3         0            1     2.0       0.0
4       yu_DCZ      10         4         0            1     1.0       1.0
...        ...     ...       ...       ...          ...     ...       ...
23031  yu_sham      71       536        12            3     3.0       1.0
23032  yu_sham      71       537        12            3     3.0       1.0
23033  yu_sham      71       538        12            3     3.0       1.0
23034  yu_sham      71       539        12            3     3.0       1.0
23035  yu_sham      71       540        12            3     3.0       1.0

[23548 rows x 7 columns]

In [ ]:
floc_raw = os.path.join(PROJECT_PATH_LOCAL, 'data', 'processed', 'behavior', 'REALValue_df.csv')

data = pd.read_csv(floc_raw)

'''# reorder columns to [monkey, injection, session, trial, block, best_targ, targ_action, Rew]
data = data[['monkey', 'injection', 'session', 'trial', 'block', 'best_targ', 'targ_action', 'Rew', 'Shift', 'bTrial']]

data['monkey'] = 'yu'
data['monkey'] = [data['monkey'][i] + '_' + data['injection'][i] for i in range(len(data))]
data.sort_values(by=['monkey', 'session', 'trial'], inplace=True)
data.drop(columns=['injection'], inplace=True)
data['session'] = data['session'].astype(str)
data.rename(columns={'trial': 'trial_id'}, inplace=True)  
data.rename(columns={'block': 'block_id'}, inplace=True)
data.rename(columns={'best_targ': 'best_target'}, inplace=True)
data.rename(columns={'targ_action': 'target'}, inplace=True)
data.rename(columns={'Rew': 'feedback'}, inplace=True)
data['block_id'] = data['block_id'] - 1
data['trial_id'] = data['trial_id'] - 1

data = data.drop(columns=['Shift', 'bTrial'])

# if tarhet is null, set feedback to null as well
data['feedback'] = np.where(data['target'].isnull(), np.nan, data['feedback'])

data = data.sort_values(by=['monkey', 'session', 'trial_id'])

floc_save = os.path.join(PROJECT_PATH_LOCAL, 'data', 'processed', 'behavior', 'behavior_yuri.pkl')
data.to_pickle(floc_save)
print(f"Saved {floc_save}")'''

data

,session,trial,monkey,injection,block,Rew,best_targ,targ_action,bTrial,Shift
0,10,1,Yuri,DCZ,1,0,1,3,1,1
1,10,2,Yuri,DCZ,1,1,1,3,2,0
2,10,3,Yuri,DCZ,1,0,1,2,3,1
3,10,4,Yuri,DCZ,1,1,1,1,4,1
4,10,5,Yuri,DCZ,1,0,1,0,5,1
...,...,...,...,...,...,...,...,...,...,...
23410,74,507,Yuri,DCZ,12,0,3,0,38,1
23411,74,508,Yuri,DCZ,12,0,3,2,39,1
23412,74,509,Yuri,DCZ,12,0,3,1,40,1
23413,74,510,Yuri,DCZ,12,0,3,1,41,0
23414,74,511,Yuri,DCZ,13,1,1,0,1,1